<a href="https://colab.research.google.com/github/Usman5-07/tempRepo/blob/main/Step_Tracker.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.options.display.float_format = '{:.2f}'.format

In [48]:
path = '/content/drive/MyDrive/Colab Notebooks/steps_tracker_dataset.csv'
df = pd.read_csv(path)

In [49]:
df.head()

,date,steps,distance_km,calories_burned,active_minutes,sleep_hours,water_intake_liters,mood
0,08/10/2022,4147,3.11,124.41,41,10.50,3.77,stressed
1,11/06/2022,323,0.24,9.69,3,6.00,1.90,sad
2,28/01/2022,6622,4.97,198.66,66,6.00,4.48,sad
3,23/03/2022,11136,8.35,334.08,111,8.00,1.08,tired
4,20/05/2022,2718,2.04,81.54,27,4.90,1.00,tired

In [50]:
df.tail()

,date,steps,distance_km,calories_burned,active_minutes,sleep_hours,water_intake_liters,mood
495,04/05/2022,17376,13.03,521.28,174,8.00,2.86,energetic
496,16/04/2022,6917,5.19,207.51,69,4.70,0.49,sad
497,08/01/2022,12247,9.19,367.41,122,9.00,0.15,happy
498,01/03/2022,8295,6.22,248.85,83,4.80,2.39,stressed
499,18/08/2022,5254,3.94,157.62,53,3.30,2.15,sad

In [51]:
df.shape

(500, 8)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 500 non-null    object
 1   steps                500 non-null    int64
 2   distance_km          500 non-null    float64
 3   calories_burned      500 non-null    float64
 4   active_minutes       500 non-null    int64
 5   sleep_hours          500 non-null    float64
 6   water_intake_liters  500 non-null    float64
 7   mood                 500 non-null    object
dtypes: float64(4), int64(2), object(2)
memory usage: 31.4+ KB

## **Observations:**

1. Average number of steps are: 10238
2. Average Distance is 7.7km.
3. Average calaries burned are about 307
4. Average active minutes are 102, which accounts for more then 1 hour and 40 mins.
5. Normal sleep is about 7.2 hours
6. Water intake is about 2.5L on an average.

In [53]:
df.describe()

,steps,distance_km,calories_burned,active_minutes,sleep_hours,water_intake_liters
count,500.00,500.00,500.00,500.00,500.00,500.00
mean,10238.57,7.68,307.16,102.41,7.29,2.51
std,5829.27,4.37,174.88,58.29,1.81,1.43
min,26.00,0.02,0.78,0.00,3.10,0.04
25%,5313.25,3.98,159.40,53.00,6.00,1.30
50%,10699.00,8.02,320.97,107.00,7.00,2.50
75%,15317.50,11.49,459.53,153.00,8.22,3.78
max,19979.00,14.98,599.37,200.00,12.00,5.00

## Observation:

About 136 records where people have walked over 15k steps.

Lets analyze there activities. Like:
- Mood.
- Sleep.

In [54]:
# Lets check how many records are there where people have walked more then 15k steps
over_15k = df[df['steps']>15000]

In [55]:
over_15k.reset_index(inplace=True)

The following table shows that 32 people are stressed, but most of the prople in this set are happy or energatic. While the number of **sad** people is the least.

In [56]:
over_15k.mood.value_counts().sort_values(ascending=False)

mood
stressed     32
energetic    31
happy        29
tired        23
sad          21
Name: count, dtype: int64

Of the 136 records with more then 15k steps 52 of these records show that these people have more then 7 hours of sleep.

In [57]:
over_7hr_sleep_greaterThen_15k_steps = over_15k[over_15k['sleep_hours']>7]

In [58]:
over_7hr_sleep_greaterThen_15k_steps.head()

,index,date,steps,distance_km,calories_burned,active_minutes,sleep_hours,water_intake_liters,mood
1,7,13/07/2022,17290,12.97,518.70,173,11.60,4.08,energetic
3,17,04/04/2022,18451,13.84,553.53,185,8.00,1.35,sad
4,22,06/08/2022,17002,12.75,510.06,170,9.00,2.92,tired
6,29,24/07/2022,15005,11.25,450.15,150,8.20,2.06,happy
7,31,23/01/2022,17812,13.36,534.36,178,8.00,1.08,stressed

This execution shows that most people who walk alot are either stressed or are tired, that might be the reason for them getting more sleep.

If we see in life the people who are stressed generally walk alot to reflect on there problems hence get tired too.

In [59]:
over_7hr_sleep_greaterThen_15k_steps.mood.value_counts().sort_values(ascending=False)

mood
stressed     15
tired        10
energetic     9
sad           9
happy         9
Name: count, dtype: int64

Observations:

This shows that most number of people are happy in the dataset followed by stressed people.

In [60]:
df.mood.value_counts().sort_values(ascending=False)

mood
happy        110
stressed     106
sad           97
energetic     97
tired         90
Name: count, dtype: int64

In [61]:
df.columns

Index(['date', 'steps', 'distance_km', 'calories_burned', 'active_minutes',
       'sleep_hours', 'water_intake_liters', 'mood'],
      dtype='object')

Following analysis shows no relation between water intake and mood because all the values lie close to each other, rather it tells us that energetic people tend to take less water as compared to tired people.

In [66]:
print("Mood vs Water Intake Average")
print("")
for mood in df['mood'].unique():
    print(f"{mood}: {df[df['mood'] == mood]['water_intake_liters'].mean():.2f}")

Mood vs Water Intake Average

stressed: 2.59
sad: 2.58
tired: 2.61
happy: 2.53
energetic: 2.22

Most calories burned by the energetic people followed by tired people (Surprizingly).

In [67]:
print("Mood vs Calories burned Average")
print("")
for mood in df['mood'].unique():
    print(f"{mood}: {df[df['mood'] == mood]['calories_burned'].mean():.2f}")

Mood vs Calories burned Average

stressed: 308.72
sad: 287.41
tired: 315.47
happy: 296.84
energetic: 329.18

Surprizingly, distance covered by people whose mood is tired is most in all 3 cases.
1. The minimum walk registered in the dataset is from the person who is tired.
2. Average is also the greatest for tired person
3. Maximum distance is also covered by the tired person.

This implies that the person walked the most might have picked mood 'tired' because of the distance.

In [74]:
print("Mood vs Distance in Kilometers Average")
print("")

for mood in df['mood'].unique():
    print(f"Minimum: {mood}: {df[df['mood'] == mood]['distance_km'].min():.2f}")

    print(f"Average: {mood}: {df[df['mood'] == mood]['distance_km'].mean():.2f}")


    print(f"Maximum: {mood}: {df[df['mood'] == mood]['distance_km'].max():.2f}")
    print("")

Mood vs Distance in Kilometers Average

Minimum: stressed: 0.02
Average: stressed: 7.72
Maximum: stressed: 14.65

Minimum: sad: 0.09
Average: sad: 7.18
Maximum: sad: 14.98

Minimum: tired: 0.35
Average: tired: 7.89
Maximum: tired: 14.96

Minimum: happy: 0.12
Average: happy: 7.42
Maximum: happy: 14.90

Minimum: energetic: 0.17
Average: energetic: 8.23
Maximum: energetic: 14.98

In [76]:
df[df['distance_km'] == 0.35]
df[df['distance_km'] == 7.89]
df[df['distance_km'] == 14.96]

,date,steps,distance_km,calories_burned,active_minutes,sleep_hours,water_intake_liters,mood
45,21/05/2022,19940,14.96,598.20,199,6.00,0.24,tired
245,25/10/2022,19949,14.96,598.47,199,6.00,2.94,tired

In [86]:
less_than_1L = df[df['water_intake_liters']<1]
less_than_1L.shape

(97, 8)

In [91]:
less_than_1L[less_than_1L['mood'] == 'sad'].shape

(18, 8)

Most of the people are happy and energetic in the dataset where the water intake is less then 1 liter.

`**[46% percent of people are Happy and Energetic]**`

In [93]:
for mood in df['mood'].unique():
    print(f"{mood}: {less_than_1L[less_than_1L['mood'] == mood].shape}")

stressed: (19, 8)
sad: (18, 8)
tired: (15, 8)
happy: (21, 8)
energetic: (24, 8)